title: Shashidhar Halady
description: >-
  Articles in English and ಕನ್ನಡ (Kannada)
url: "https://shashidharhalady.github.io"
baseurl: ""
lang: en
theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
